# Generated by Django 2.2.2 on 2019-07-11 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('like', models.BooleanField()),
                ('strong', models.FloatField()),
                ('long', models.FloatField()),
                ('heavy', models.FloatField()),
                ('complex', models.FloatField()),
                ('gorgeous', models.FloatField()),
                ('sweet', models.FloatField()),
                ('bitter', models.FloatField()),
                ('sour', models.FloatField()),
                ('umami', models.FloatField()),
                ('aftertaste', models.FloatField()),
                ('roundness', models.FloatField()),
                ('smooth_texture', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tea_name', models.CharField(max_length=64, verbose_name='tea name')),
                ('category', models.CharField(max_length=64)),
                ('strong', models.FloatField()),
                ('long', models.FloatField()),
                ('heavy', models.FloatField()),
                ('complex', models.FloatField()),
                ('gorgeous', models.FloatField()),
                ('sweet', models.FloatField()),
                ('bitter', models.FloatField()),
                ('sour', models.FloatField()),
                ('umami', models.FloatField()),
                ('aftertaste', models.FloatField()),
                ('roundness', models.FloatField()),
                ('smooth_texture', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=150, verbose_name='profile name')),
                ('icon', models.ImageField(upload_to='')),
                ('header', models.ImageField(upload_to='')),
                ('introduction', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('strong', models.FloatField()),
                ('long', models.FloatField()),
                ('heavy', models.FloatField()),
                ('complex', models.FloatField()),
                ('gorgeous', models.FloatField()),
                ('sweet', models.FloatField()),
                ('bitter', models.FloatField()),
                ('sour', models.FloatField()),
                ('umami', models.FloatField()),
                ('aftertaste', models.FloatField()),
                ('roundness', models.FloatField()),
                ('smooth_texture', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='web_service.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='text')),
                ('img_1', models.ImageField(upload_to='', verbose_name='image 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image 2')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image 3')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image 4')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='web_service.Evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='web_service.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='web_service.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='web_service.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='web_service.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='tea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea', to='web_service.Tea'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='web_service.UserProfile'),
        ),
    ]
