# Generated by Django 2.2.2 on 2019-07-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='category',
            field=models.CharField(choices=[('W', '白茶'), ('Y', '黄茶'), ('G', '緑茶'), ('Bu', '青茶'), ('R', '紅茶'), ('Bl', '黒茶')], max_length=10),
        ),
        migrations.AlterField(
            model_name='preference',
            name='category',
            field=models.CharField(choices=[('W', '白茶'), ('Y', '黄茶'), ('G', '緑茶'), ('Bu', '青茶'), ('R', '紅茶'), ('Bl', '黒茶')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tea',
            name='aftertaste',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='bitter',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='category',
            field=models.CharField(choices=[('W', '白茶'), ('Y', '黄茶'), ('G', '緑茶'), ('Bu', '青茶'), ('R', '紅茶'), ('Bl', '黒茶')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tea',
            name='complex',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='gorgeous',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='heavy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='long',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='roundness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='smooth_texture',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='sour',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='strong',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='sweet',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='umami',
            field=models.FloatField(null=True),
        ),
    ]
