# Generated by Django 2.2.2 on 2019-07-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0002_auto_20190711_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='aftertaste',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='bitter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='complex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='gorgeous',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='heavy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='roundness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='smooth_texture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='sour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='strong',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='sweet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tea',
            name='umami',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
