# Generated by Django 2.2.2 on 2019-07-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0003_auto_20190711_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_1',
            field=models.ImageField(upload_to='img_1', verbose_name='image 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='img_2', verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='img_3', verbose_name='image 3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='img_4', verbose_name='image 4'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='header',
            field=models.ImageField(upload_to='header'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(upload_to='icon'),
        ),
    ]
